# Generated by Django 4.1.4 on 2022-12-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_country_rang_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.rang'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='self_information',
            field=models.TextField(blank=True, default=''),
        ),
    ]
