# Generated by Django 4.1.4 on 2023-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/profile_avatar/default_avatar.jpg', upload_to='images/profile_avatar'),
        ),
    ]
